[versions]
kotlin = "2.2.21"
changelog = "2.5.0"
gradleIntelliJPlugin = "2.10.5"
qodana = "2025.2.3"
kover = "0.9.3"

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij.platform", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }